name: YMH_Projesi
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scikit-learn
  - scipy
  - joblib
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - beautifulsoup4==4.13.3
      - blinker==1.9.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - distro==1.9.0
      - exceptiongroup==1.2.2
      - flask==3.1.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - iniconfig==2.1.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.9.0
      - markupsafe==3.0.2
      - openai==1.68.2
      - packaging==25.0
      - pluggy==1.6.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pytest==8.3.5
      - pytest-flask==1.3.0
      - python-dotenv==1.1.0
      - requests==2.32.3
      - sniffio==1.3.1
      - soupsieve==2.6
      - tomli==2.2.1
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - werkzeug==3.1.3